export const locations = [
  "California",
  "Florida",
  "Kerala",
  "New York",
  "Telangana",
  "Texas",
  "Washington",
];

export const degrees = [
  "Associate's Degree",
  "Bachelor's Degree",
  "Diploma",
  "Doctorate (PhD)",
  "High School Diploma",
  "JD (Law)",
  "Master's Degree",
  "MBA",
  "MD (Medical Doctor)",
  "Professional Certificate",
];

export const fieldsOfStudy = [
  "Artificial Intelligence",
  "Arts & Design",
  "Business Administration",
  "Civil Engineering",
  "Computer Science",
  "Data Science",
  "Economics",
  "Electrical Engineering",
  "Finance",
  "Information Technology",
  "Law",
  "Marketing",
  "Mechanical Engineering",
  "Medicine",
  "Psychology",
];

export const institutions = [
  "BITS Pilani",
  "Cambridge University",
  "Harvard University",
  "IIM Ahmedabad",
  "IIM Bangalore",
  "IIT Bombay",
  "IIT Delhi",
  "IIT Madras",
  "MIT",
  "NIT Trichy",
  "National University of Singapore",
  "Others",
  "Oxford University",
  "Stanford University",
];

export const jobTitles = [
  "Backend Developer",
  "Business Analyst",
  "Cloud Architect",
  "Consultant",
  "Data Analyst",
  "Data Scientist",
  "DevOps Engineer",
  "Financial Analyst",
  "Frontend Developer",
  "Full Stack Developer",
  "HR Manager",
  "Marketing Manager",
  "Others",
  "Product Manager",
  "Project Manager",
  "Self-Employed",
  "Senior Software Engineer",
  "Software Engineer",
  "Student",
  "UI Designer",
  "UX Designer",
  "Unemployed",
];

export const industries = [
  "Automotive",
  "Consulting",
  "E-commerce",
  "Education",
  "Energy",
  "Finance & Banking",
  "Government",
  "Healthcare",
  "Information Technology",
  "Manufacturing",
  "Media & Entertainment",
  "Pharmaceuticals",
  "Real Estate",
  "Retail",
  "Telecommunications",
];

export const skillsList = [
  "AWS",
  "Communication",
  "Data Analysis",
  "Docker",
  "Java",
  "JavaScript",
  "Kubernetes",
  "Leadership",
  "Machine Learning",
  "Node.js",
  "Problem Solving",
  "Project Management",
  "Python",
  "React",
  "SQL",
];
