export const countries = [
  "India",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Japan",
  "China",
  "Brazil",
  "Singapore",
  "UAE",
  "Netherlands",
  "Sweden",
  "Switzerland",
];

export const states = [
  "Maharashtra",
  "Karnataka",
  "Tamil Nadu",
  "Gujarat",
  "Rajasthan",
  "Delhi",
  "Uttar Pradesh",
  "West Bengal",
  "Kerala",
  "Telangana",
  "California",
  "Texas",
  "New York",
  "Florida",
  "Washington",
];

export const degrees = [
  "High School Diploma",
  "Associate's Degree",
  "Bachelor's Degree",
  "Master's Degree",
  "Doctorate (PhD)",
  "MBA",
  "MD (Medical Doctor)",
  "JD (Law)",
  "Professional Certificate",
  "Diploma",
];

export const fieldsOfStudy = [
  "Computer Science",
  "Information Technology",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Business Administration",
  "Economics",
  "Finance",
  "Marketing",
  "Psychology",
  "Medicine",
  "Law",
  "Arts & Design",
  "Data Science",
  "Artificial Intelligence",
];

export const institutions = [
  "IIT Bombay",
  "IIT Delhi",
  "IIT Madras",
  "IIM Ahmedabad",
  "IIM Bangalore",
  "BITS Pilani",
  "NIT Trichy",
  "MIT",
  "Stanford University",
  "Harvard University",
  "Oxford University",
  "Cambridge University",
  "National University of Singapore",
  "Others",
];

export const jobTitles = [
  "Software Engineer",
  "Senior Software Engineer",
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "Data Scientist",
  "Data Analyst",
  "Product Manager",
  "Project Manager",
  "UX Designer",
  "UI Designer",
  "DevOps Engineer",
  "Cloud Architect",
  "Business Analyst",
  "Marketing Manager",
  "HR Manager",
  "Financial Analyst",
  "Consultant",
  "Others",
  "Unemployed",
  "Student",
  "Self-Employed",
];

export const industries = [
  "Information Technology",
  "Finance & Banking",
  "Healthcare",
  "Education",
  "E-commerce",
  "Manufacturing",
  "Consulting",
  "Retail",
  "Telecommunications",
  "Media & Entertainment",
  "Real Estate",
  "Automotive",
  "Pharmaceuticals",
  "Energy",
  "Government",
];

export const skillsList = [
  "JavaScript",
  "Python",
  "React",
  "Node.js",
  "Java",
  "SQL",
  "AWS",
  "Docker",
  "Kubernetes",
  "Machine Learning",
  "Data Analysis",
  "Project Management",
  "Communication",
  "Leadership",
  "Problem Solving",
];
